# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05dfff1c0da5b97a41f966ce765b72404bddbae531e94a397904be9d455e68f0a9d41ce61497208667d7baeb8092cad58a98892627b05564ff2cb4a4d71a1fb3

test:
  secret_key_base: 7580918552cec0d7e0b5a6bba4fc0d6461b39eecd08a8edb2695fa4c6b8cd8b256622134efa283e44b6c36e5c2fb238de302dfaa91c68cda753f0cf9f1f4f297

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
